// Manifest validation.
//
// The Studio is a GUI, so most structural mistakes can't be typed by hand —
// but manifests are also hand-edited, generated by scripts, and carried
// forward across schema revisions, and a merchant finding out at checkout
// that a swatch id was a typo is unacceptable. Every reference is resolved
// here: a manifest that passes is one the runtime can render without a single
// defensive null check.
//
// Errors block rendering. Warnings don't — an unknown field from a newer
// Studio must degrade, not fail.

import type {
  Manifest, Option, ColourOption, ChoiceOption, UploadOption, TextOption,
  Part, AxisPlacement,
} from './types.ts';
import { TEXT_FONTS } from './types.ts';

export interface Issue {
  path: string;
  message: string;
}

export interface ValidationResult {
  ok: boolean;
  errors: Issue[];
  warnings: Issue[];
}

const isColour = (o: Option): o is ColourOption => o.type === 'colour';
const isChoice = (o: Option): o is ChoiceOption => o.type === 'choice';
const isUpload = (o: Option): o is UploadOption => o.type === 'upload';
const isText = (o: Option): o is TextOption => o.type === 'text';

const HEX = /^#[0-9a-fA-F]{6}$/;
const ID = /^[a-z0-9][a-z0-9-]*$/;

export function validateManifest(input: unknown): ValidationResult {
  const errors: Issue[] = [];
  const warnings: Issue[] = [];
  const err = (path: string, message: string) => errors.push({ path, message });
  const warn = (path: string, message: string) => warnings.push({ path, message });

  if (!input || typeof input !== 'object') {
    return { ok: false, errors: [{ path: '', message: 'manifest must be an object' }], warnings };
  }
  const m = input as Partial<Manifest>;

  if (m.schema !== 1) err('schema', `unsupported schema version ${JSON.stringify(m.schema)} — this runtime reads 1`);
  if (!m.id) err('id', 'required');
  else if (!ID.test(m.id)) err('id', 'must be lowercase letters, digits and hyphens');
  if (!m.name) err('name', 'required');
  if (m.units !== 'mm') err('units', 'must be "mm" — the import pipeline normalises every model to millimetres');

  // ── unique ids ────────────────────────────────────────────────────────────
  const dupes = (list: Array<{ id?: string }> | undefined, path: string) => {
    const seen = new Set<string>();
    (list ?? []).forEach((item, i) => {
      if (!item?.id) { err(`${path}[${i}].id`, 'required'); return; }
      if (seen.has(item.id)) err(`${path}[${i}].id`, `duplicate id "${item.id}"`);
      seen.add(item.id);
    });
    return seen;
  };

  const modelIds = dupes(m.models, 'models');
  const partIds = dupes(m.parts, 'parts');
  const paletteIds = dupes(m.palettes, 'palettes');
  const optionIds = dupes(m.options, 'options');

  // Empty is a WARNING, not an error: the Studio starts from an empty
  // project and every edit re-validates — an empty manifest must be legal to
  // hold, just not sensible to ship.
  if (!m.models?.length) warn('models', 'no model sources yet — add parts before publishing');
  if (!m.parts?.length) warn('parts', 'no parts yet — add parts before publishing');
  if (!m.pricing?.currency) err('pricing.currency', 'required — the host cart needs to know what the deltas are denominated in');

  (m.models ?? []).forEach((s, i) => {
    if (!s?.url) err(`models[${i}].url`, 'required');
  });

  // ── scene ─────────────────────────────────────────────────────────────────
  if (m.scene) {
    const range = (key: 'exposure' | 'environmentIntensity' | 'shadowOpacity', lo: number, hi: number) => {
      const v = m.scene![key];
      if (v !== undefined && (typeof v !== 'number' || !Number.isFinite(v) || v < lo || v > hi)) {
        err(`scene.${key}`, `must be a number between ${lo} and ${hi}`);
      }
    };
    range('exposure', 0.25, 3);
    range('environmentIntensity', 0, 2);
    range('shadowOpacity', 0, 1);
  }

  // ── parts ─────────────────────────────────────────────────────────────────
  const anchorTargets = new Map<string, string[]>(); // partId → parts it anchors to

  (m.parts ?? []).forEach((p: Part, i) => {
    const at = `parts[${i}]`;
    if (!p?.label) err(`${at}.label`, 'required');
    const [source, mesh] = (p?.mesh ?? '').split('#');
    if (!source || !mesh) err(`${at}.mesh`, 'must be "<modelId>#<meshName>"');
    else if (!modelIds.has(source)) err(`${at}.mesh`, `unknown model source "${source}"`);

    if (p?.material?.fixedColour && !HEX.test(p.material.fixedColour)) {
      err(`${at}.material.fixedColour`, `"${p.material.fixedColour}" is not #RRGGBB`);
    }

    const deps: string[] = [];
    for (const axis of ['x', 'y', 'z'] as const) {
      const a = p?.placement?.[axis] as AxisPlacement | undefined;
      if (!a?.to || a.to === 'origin') continue;
      const [ref, edge] = a.to.split(':');
      if (!['min', 'center', 'max'].includes(edge)) {
        err(`${at}.placement.${axis}.to`, `edge must be min|center|max, got "${edge}"`);
      } else if (ref === p.id) {
        err(`${at}.placement.${axis}.to`, 'a part cannot anchor to itself — use "origin"');
      } else if (!partIds.has(ref)) {
        err(`${at}.placement.${axis}.to`, `unknown part "${ref}"`);
      } else {
        deps.push(ref);
      }
    }
    if (p?.id) anchorTargets.set(p.id, deps);

    const scale = p?.placement?.scale;
    if (scale && scale.some((v) => !(v > 0))) {
      err(`${at}.placement.scale`, 'every axis must be greater than zero');
    }

    if (p?.visibleWhen) {
      if (!optionIds.has(p.visibleWhen.option)) {
        err(`${at}.visibleWhen.option`, `unknown option "${p.visibleWhen.option}"`);
      }
      if (!p.visibleWhen.equals?.length) {
        err(`${at}.visibleWhen.equals`, 'must list at least one value, otherwise the part can never show');
      }
    }
  });

  // A placement cycle would deadlock layout, so catch it before the runtime does.
  for (const cycle of findCycles(anchorTargets)) {
    err('parts', `placement anchors form a cycle: ${cycle.join(' → ')}`);
  }

  // ── groups ────────────────────────────────────────────────────────────────
  const groupIds = dupes(m.groups, 'groups');
  void groupIds;
  const grouped = new Map<string, string>();
  (m.groups ?? []).forEach((g, i) => {
    if (!g?.label) err(`groups[${i}].label`, 'required');
    if (!g?.parts?.length || g.parts.length < 2) err(`groups[${i}].parts`, 'a group needs at least two parts');
    (g?.parts ?? []).forEach((pid, j) => {
      if (!partIds.has(pid)) err(`groups[${i}].parts[${j}]`, `unknown part "${pid}"`);
      else if (grouped.has(pid)) err(`groups[${i}].parts[${j}]`, `part "${pid}" is already in group "${grouped.get(pid)}"`);
      else grouped.set(pid, g.id);
    });
  });

  // ── palettes ──────────────────────────────────────────────────────────────
  const swatchIds = new Map<string, Set<string>>();
  (m.palettes ?? []).forEach((pal, i) => {
    const at = `palettes[${i}]`;
    if (!pal?.swatches?.length) { err(`${at}.swatches`, 'a palette needs at least one swatch'); return; }
    const ids = new Set<string>();
    pal.swatches.forEach((s, j) => {
      if (!s?.id) err(`${at}.swatches[${j}].id`, 'required');
      else if (ids.has(s.id)) err(`${at}.swatches[${j}].id`, `duplicate swatch id "${s.id}"`);
      ids.add(s?.id);
      if (!s?.name) warn(`${at}.swatches[${j}].name`, 'no name — the cart will show a raw hex code on the order');
      if (!HEX.test(s?.hex ?? '')) err(`${at}.swatches[${j}].hex`, `"${s?.hex}" is not #RRGGBB`);
    });
    if (pal.id) swatchIds.set(pal.id, ids);
  });

  // ── options ───────────────────────────────────────────────────────────────
  const colourOptionIds = new Set(
    (m.options ?? []).filter((o) => o && isColour(o)).map((o) => o.id),
  );
  const linkedTo = new Map<string, string[]>();

  (m.options ?? []).forEach((o: Option, i) => {
    const at = `options[${i}]`;
    if (!o?.label) err(`${at}.label`, 'required');

    if (o && isColour(o)) {
      if (!o.parts?.length) err(`${at}.parts`, 'a colour option must paint at least one part');
      (o.parts ?? []).forEach((pid, j) => {
        if (!partIds.has(pid)) err(`${at}.parts[${j}]`, `unknown part "${pid}"`);
      });

      const usesPalette = (o.source ?? 'palette') === 'palette';
      if (usesPalette) {
        if (!o.palette) err(`${at}.palette`, 'required unless source is "used"');
        else if (!paletteIds.has(o.palette)) err(`${at}.palette`, `unknown palette "${o.palette}"`);
      } else if (o.palette) {
        warn(`${at}.palette`, 'ignored when source is "used"');
      }

      // A default may be a swatch id or "@otherOption" (start matched).
      if (!o.default) {
        err(`${at}.default`, 'required — the embed has to render something before the customer touches it');
      } else if (o.default.startsWith('@')) {
        const ref = o.default.slice(1);
        if (!colourOptionIds.has(ref)) err(`${at}.default`, `"@${ref}" does not name a colour option`);
        else linkedTo.set(o.id, [ref]);
      } else if (usesPalette && o.palette && swatchIds.has(o.palette) && !swatchIds.get(o.palette)!.has(o.default)) {
        err(`${at}.default`, `"${o.default}" is not a swatch in palette "${o.palette}"`);
      }

      if (o.linkedTo) {
        if (!colourOptionIds.has(o.linkedTo)) err(`${at}.linkedTo`, `unknown colour option "${o.linkedTo}"`);
        else if (o.linkedTo === o.id) err(`${at}.linkedTo`, 'an option cannot link to itself');
        else linkedTo.set(o.id, [...(linkedTo.get(o.id) ?? []), o.linkedTo]);
      }

      if (o.custom?.allowed && o.custom.priceDelta == null) {
        warn(`${at}.custom.priceDelta`, 'custom colours are allowed but carry no surcharge — intended?');
      }
      if (o.source === 'used' && o.custom?.allowed) {
        err(`${at}.custom`, 'a "used" option can only match colours already on the product, so it cannot accept a custom one');
      }
    } else if (o && isChoice(o)) {
      if (!o.choices?.length) err(`${at}.choices`, 'required');
      const ids = new Set((o.choices ?? []).map((c) => c?.id));
      if (ids.size !== (o.choices ?? []).length) err(`${at}.choices`, 'choice ids must be unique');
      if (!ids.has(o.default)) err(`${at}.default`, `"${o.default}" is not one of the choices`);
    } else if (o && isUpload(o)) {
      if (!partIds.has(o.part)) err(`${at}.part`, `unknown part "${o.part}"`);
      if (o.maxBytes != null && !(o.maxBytes > 0)) err(`${at}.maxBytes`, 'must be greater than zero');
    } else if (o && isText(o)) {
      if (!partIds.has(o.part)) err(`${at}.part`, `unknown part "${o.part}"`);
      const vec3 = (key: 'origin' | 'normal') => {
        const v = o[key];
        if (!Array.isArray(v) || v.length !== 3 || v.some((n) => typeof n !== 'number' || !Number.isFinite(n))) {
          err(`${at}.${key}`, 'must be [x, y, z] millimetres in the part\'s local space');
          return false;
        }
        return true;
      };
      vec3('origin');
      if (vec3('normal') && Math.hypot(...o.normal) < 1e-6) {
        err(`${at}.normal`, 'must not be a zero vector — it is the extrusion direction');
      }
      if (o.font != null && !TEXT_FONTS.includes(o.font)) {
        err(`${at}.font`, `unknown font "${o.font}" — bundled fonts are ${TEXT_FONTS.join(', ')}`);
      }
      if (!(o.sizeMm > 0) || o.sizeMm > 200) err(`${at}.sizeMm`, 'must be between 0 and 200 millimetres');
      if (!(o.depthMm >= 0.2) || o.depthMm > 50) err(`${at}.depthMm`, 'must be between 0.2 and 50 millimetres');
      const sink = o.sinkMm ?? 0;
      if (!(sink >= 0) || !Number.isFinite(sink)) err(`${at}.sinkMm`, 'must be zero or more');
      else if (Number.isFinite(o.depthMm) && sink >= o.depthMm) {
        err(`${at}.sinkMm`, 'must be less than depthMm — sinking the whole extrusion leaves nothing visible');
      }
      if (o.rotationDeg != null && !Number.isFinite(o.rotationDeg)) err(`${at}.rotationDeg`, 'must be a number');
      if (o.maxLength != null && (!Number.isInteger(o.maxLength) || o.maxLength < 1 || o.maxLength > 60)) {
        err(`${at}.maxLength`, 'must be a whole number between 1 and 60');
      }
      if (o.placeholder && o.placeholder.length > (o.maxLength ?? 20)) {
        warn(`${at}.placeholder`, 'longer than maxLength — customers cannot type it back');
      }
      if (o.colourHex != null && !HEX.test(o.colourHex)) {
        err(`${at}.colourHex`, `"${o.colourHex}" is not #RRGGBB`);
      }
      if (o.perChar) {
        if (o.perChar.mode != null && !['line', 'circle'].includes(o.perChar.mode)) {
          err(`${at}.perChar.mode`, 'must be "line" or "circle"');
        }
        if (o.perChar.axis != null && ![0, 1, 2].includes(o.perChar.axis)) {
          err(`${at}.perChar.axis`, 'must be 0 (x), 1 (y) or 2 (z)');
        }
        const gap = o.perChar.gapMm;
        if (gap != null && (typeof gap !== 'number' || !Number.isFinite(gap) || gap < 0 || gap > 500)) {
          err(`${at}.perChar.gapMm`, 'must be a number between 0 and 500 millimetres');
        }
        const step = o.perChar.stepDeg;
        if (step != null && (typeof step !== 'number' || !Number.isFinite(step) || step < 1 || step > 180)) {
          err(`${at}.perChar.stepDeg`, 'must be a number between 1 and 180 degrees');
        }
      }
    } else if (o) {
      warn(`${at}.type`, `unknown option type "${(o as { type?: string }).type}" — it will be skipped`);
    }
  });

  for (const cycle of findCycles(linkedTo)) {
    err('options', `colour links form a cycle: ${cycle.join(' → ')}`);
  }

  // Parts nobody can colour are legal (fixed trim) but usually a mistake.
  const painted = new Set((m.options ?? []).flatMap((o) => (o && isColour(o) ? o.parts ?? [] : [])));
  (m.parts ?? []).forEach((p, i) => {
    if (p?.id && !painted.has(p.id) && !p.material?.fixedColour) {
      warn(`parts[${i}]`, `"${p.id}" has no colour option and no fixedColour — it will render in the default grey`);
    }
  });

  return { ok: errors.length === 0, errors, warnings };
}

/** Every cycle in a dependency map, each reported once from its lowest node. */
function findCycles(graph: Map<string, string[]>): string[][] {
  const cycles: string[][] = [];
  const state = new Map<string, 'open' | 'done'>();
  const stack: string[] = [];

  const walk = (node: string) => {
    if (state.get(node) === 'done') return;
    if (state.get(node) === 'open') {
      const from = stack.indexOf(node);
      if (from !== -1) cycles.push([...stack.slice(from), node]);
      return;
    }
    state.set(node, 'open');
    stack.push(node);
    for (const next of graph.get(node) ?? []) walk(next);
    stack.pop();
    state.set(node, 'done');
  };

  for (const node of graph.keys()) walk(node);
  return cycles;
}

/** Throwing wrapper for build scripts, where a bad manifest should stop the job. */
export function assertManifest(input: unknown): Manifest {
  const { ok, errors } = validateManifest(input);
  if (!ok) {
    throw new Error(`invalid manifest:\n${errors.map((e) => `  ${e.path || '<root>'}: ${e.message}`).join('\n')}`);
  }
  return input as Manifest;
}
